query fetch {
  queryInternationalcooperationContents {
    data: flatData {
      title
      description
      vinculoTitle
      cooperations {
        fullName
        acronym
        participationType
        category
        link
        iniqRelation
      }
    }
  }
}
