query fetch {
  queryInternationalcooperationContents {
    data: flatData {
      title
      description
      cooperations {
        fullName
        acronym
        participationType
        link
      }
    }
  }
}
