query fetch {
  queryRequirementmetrologyContents {
    data: flatData {
    rules {
      title
      description
      rules {
        title
      }
      model {
        title
        description
        url {
          url
        }
      }
    }
  }
}
}
