query fetch {
  queryHomepremioqualidadeContents {
    data: flatData {
      leader {
        image {
          url
        }
        name
        position
      }
      titleresponsible
      message
      titlequalitypolicy
      qualitypolicy
      panelhead {
        eyebrow
        title
        description
      }
      awarddescription
    }
  }
  queryPremioEditionsContents {
    data: flatData {
      editions {
        year
        title
        description
        isOpen
        deadline
        requirements
        dossierDescription
        winners {
          organization
          sector
          year
        }
      }
    }
  }
}
