query fetch {
  queryRegulationsContents {
    id
    data: flatData {
      title
      description
      reference
      date
      version
      price
      estado
      category {
        id
        flatData {
          title
        }
      }
      document {
        url
      }
    }
  }
}
