query fetch {
  queryRegulationequivalentContents {
    data: flatData {
      title
      description
      equivalents {
        title
        reference
        country
        organism
        estado
        category {
          id
          flatData {
            title
          }
        }
      }
    }
  }
}
