query fetch {
  queryHomeregulamentosContents {
    data: flatData {
      leader {
        image {
          url
        }
        name
        position
      }
      titleresponsible
      message
      titlequalityPolicy
      qualityPolicy
      panelHead {
        eyebrow
        title
        description
      }
      domains {
        icon
        title
        description
        points
      }
    }
  }
  queryRegulamentosContents {
    data: flatData {
      regulations {
        code
        name
        productCategory
        description
        publicationDate
        version
        pdfUrl
      }
    }
  }
}
