query fetch {
  queryPublicconsultationContents {
   data: flatData {
    title
    description
    rules {
      title
      description
      reference
      date
      category {
        id
      }
    }
  }
  }
}
