query fetch {
  queryStandardContents {
    id
    data: flatData {
      title
      reference
      price
      ics
      ano
      estado
      category {
        id
        flatData {
          title
        }
      }
    }
  }
}
