query fetch {
  queryHomeregisterContents {
    data: flatData {
      leader {
        image {
          url
        }
        name
        position
        phoneNumber
        titleresponsible
       message
       titlequalityPolicy
       qualityPolicy
      }
    }
  }
}
